=== JohnDave06/tecweb/practicas/p13/serviciovod.dtd
<!ELEMENT serviciovod (peliculas, programas)>
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (titulo, director, año)>
<!ELEMENT programas (programa+)>
<!ELEMENT programa (titulo, canal, temporada)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT canal (#PCDATA)>
<!ELEMENT temporada (#PCDATA)>

=== JohnDave06/tecweb/practicas/p13/serviciovod2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE serviciovod SYSTEM "serviciovod.dtd">
<serviciovod>
    <peliculas>
        <pelicula>
            <titulo>Matrix</titulo>
            <director>Lana Wachowski</director>
            <año>1999</año>
        </pelicula>
    </peliculas>
    <programas>
        <programa>
            <titulo>Dark</titulo>
            <canal>Netflix</canal>
            <temporada>3</temporada>
        </programa>
    </programas>
</serviciovod>
