=== JohnDave06/tecweb/practicas/p13/serviciovod_ep.dtd
<!ENTITY % region "(MEX|USA|ESP|ARG|KOR)">

<!ELEMENT serviciovod (peliculas, series)>
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (titulo, director, año)>
<!ATTLIST peliculas region %region; "USA">

<!ELEMENT series (programa+)>
<!ELEMENT programa (titulo, canal, temporada)>
<!ATTLIST series region %region; "USA">

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT canal (#PCDATA)>
<!ELEMENT temporada (#PCDATA)>

=== JohnDave06/tecweb/practicas/p13/serviciovod4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE serviciovod SYSTEM "serviciovod_ep.dtd">
<serviciovod>
    <peliculas region="MEX">
        <pelicula>
            <titulo>Parasite</titulo>
            <director>Bong Joon-ho</director>
            <año>2019</año>
        </pelicula>
    </peliculas>
    <series region="KOR">
        <programa>
            <titulo>Squid Game</titulo>
            <canal>Netflix</canal>
            <temporada>1</temporada>
        </programa>
    </series>
</serviciovod>
